import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'platform-overview',
      label: 'Platform Overview',
    },
    {
      type: 'doc',
      id: 'architecture',
      label: 'Architecture',
    },
    {
      type: 'category',
      label: 'Getting Started',
      key: 'platform-getting-started',
      collapsible: true,
      collapsed: true,
      items: [
        'getting-started/create-account',
        'getting-started/install-cli',
        'getting-started/first-application',
        'getting-started/platform-architecture-overview',
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Applications',
          collapsible: true,
          collapsed: true,
          items: [
            'build/applications/overview',
            'build/applications/architecture',
            'build/applications/creating-applications',
            'build/applications/routing-and-rules',
            'build/applications/deployment',
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Overview',
              collapsible: true,
              collapsed: false,
              items: [
                'build/functions/overview/what-are-functions',
                'build/functions/overview/when-to-use-functions',
                'build/functions/overview/functions-in-platform-architecture',
              ],
            },
            {
              type: 'category',
              label: 'Architecture',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/architecture/execution-model',
                'build/functions/architecture/runtime-environment',
                'build/functions/architecture/request-lifecycle',
                'build/functions/architecture/how-functions-interact',
              ],
            },
            {
              type: 'category',
              label: 'Getting Started',
              key: 'functions-getting-started',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/getting-started/prerequisites',
                'build/functions/getting-started/create-function',
                'build/functions/getting-started/deploy-function',
                'build/functions/getting-started/test-function',
              ],
            },
            {
              type: 'category',
              label: 'Development',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/development/function-structure',
                'build/functions/development/handling-requests-and-responses',
                'build/functions/development/environment-variables',
                'build/functions/development/calling-external-apis',
                'build/functions/development/local-development',
              ],
            },
            {
              type: 'category',
              label: 'Function Instances',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/function-instances/what-is-a-function-instance',
                'build/functions/function-instances/creating-instances',
                'build/functions/function-instances/linking-instances',
              ],
            },
            {
              type: 'category',
              label: 'Integration',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/integration/rules-engine-integration',
                'build/functions/integration/application-integration',
                'build/functions/integration/request-processing-flow',
              ],
            },
            {
              type: 'category',
              label: 'Observability',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/observability/logs',
                'build/functions/observability/debugging',
                'build/functions/observability/metrics',
              ],
            },
            {
              type: 'category',
              label: 'Advanced Topics',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/advanced/webassembly',
                'build/functions/advanced/ai-integrations',
                'build/functions/advanced/performance-optimization',
              ],
            },
            'build/functions/limits',
            {
              type: 'category',
              label: 'Runtime Reference',
              collapsible: true,
              collapsed: true,
              items: [
                'build/functions/runtime-reference/runtime-apis',
                'build/functions/runtime-reference/event-handlers',
                'build/functions/runtime-reference/configuration',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Edge Storage',
          collapsible: true,
          collapsed: true,
          items: [
            'build/edge-storage/overview',
            'build/edge-storage/buckets',
            'build/edge-storage/uploading-objects',
            'build/edge-storage/accessing-objects',
            'build/edge-storage/permissions',
          ],
        },
        {
          type: 'category',
          label: 'Databases',
          collapsible: true,
          collapsed: true,
          items: [
            'build/databases/overview',
            'build/databases/creating-databases',
            'build/databases/querying-data',
            'build/databases/edge-access',
            'build/databases/limits',
          ],
        },
        {
          type: 'category',
          label: 'AI',
          collapsible: true,
          collapsed: true,
          items: [
            'build/ai/overview',
            'build/ai/ai-models',
            'build/ai/ai-agents',
            'build/ai/running-models-at-edge',
            'build/ai/integrating-with-functions',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deliver',
      collapsible: true,
      collapsed: true,
      items: [
        'deliver/overview',
        'deliver/cache',
        'deliver/origins',
        'deliver/routing',
      ],
    },
    {
      type: 'category',
      label: 'Secure',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'WAF',
          collapsible: true,
          collapsed: true,
          items: [
            'secure/waf/overview',
            'secure/waf/rules',
            'secure/waf/managed-rules',
            'secure/waf/custom-rules',
          ],
        },
        {
          type: 'category',
          label: 'Bot Protection',
          collapsible: true,
          collapsed: true,
          items: [
            'secure/bot-protection/overview',
            'secure/bot-protection/detection',
            'secure/bot-protection/policies',
          ],
        },
        {
          type: 'category',
          label: 'DDoS Protection',
          collapsible: true,
          collapsed: true,
          items: [
            'secure/ddos-protection/overview',
            'secure/ddos-protection/mitigation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Observe',
      collapsible: true,
      collapsed: true,
      items: [
        'observe/overview',
        'observe/logs',
        'observe/metrics',
        'observe/alerts',
      ],
    },
    {
      type: 'category',
      label: 'Network',
      collapsible: true,
      collapsed: true,
      items: [
        'network/overview',
        'network/regions',
        'network/points-of-presence',
        'network/traffic-routing',
      ],
    },
    {
      type: 'category',
      label: 'Management',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'CLI',
          collapsible: true,
          collapsed: true,
          items: [
            'management/cli/installation',
            'management/cli/commands',
            'management/cli/deployment',
          ],
        },
        {
          type: 'category',
          label: 'API',
          collapsible: true,
          collapsed: true,
          items: [
            'management/api/authentication',
            'management/api/endpoints',
            'management/api/examples',
          ],
        },
        {
          type: 'category',
          label: 'Terraform',
          collapsible: true,
          collapsed: true,
          items: [
            'management/terraform/overview',
            'management/terraform/providers',
            'management/terraform/resources',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: true,
      items: [
        'reference/platform-limits',
        'reference/runtime-apis',
        'reference/http-headers',
        'reference/error-codes',
      ],
    },
  ],
};

export default sidebars;
